Update

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -13,6 +13,14 @@ source ~/.local/share/omarchy/default/bash/rc
 # Set a custom prompt with the directory revealed (alternatively use https://starship.rs)
 # PS1="\W \[\e]0;\w\a\]$PS1"
 
+connect_k2() {
+  MAC="DC:2C:26:29:42:A2"
+  bluetoothctl power on
+  bluetoothctl connect $MAC
+  bluetoothctl pairable off
+  bluetoothctl discoverable off
+}
+
 if command -v tmux &>/dev/null; then
   if [[ -z "$TMUX" ]] && [[ "$PS1" ]]; then
     tmux source-file ~/.tmux.conf
@@ -20,5 +28,26 @@ if command -v tmux &>/dev/null; then
   fi
 fi
 
+if [[ $- == *i* ]]; then
+  if ! ssh-add -l >/dev/null 2>&1; then
+    eval "$(ssh-agent -s)" >/dev/null 2>&1
+
+    for key in "$HOME/.ssh"/*; do
+      [[ -f "$key" ]] || continue
+      case "$key" in
+        *.pub | *-cert.pub) continue ;;
+      esac
+
+      if grep -Iq "PRIVATE KEY" "$key" 2>/dev/null || grep -Iq "BEGIN SSH2 ENCRYPTED PRIVATE KEY" "$key" 2>/dev/null; then
+        if ! ssh-add "$key" >/dev/null 2>&1; then
+          echo "ssh-add krävde lösenfras/failed för: $key"
+        fi
+      fi
+    done
+  fi
+fi
+
 export VISUAL=nvim
 export EDITOR="$VISUAL"
+. "/home/johan/.deno/env"
+
